<?php
	Bugs::actions(
		'view_profile'
	);
	Router::paths(array(
		'/~{user}'=>function($res,$args){
			$res->write(
				Bugs::template('user')
					->run(Bugs::user($args->user))
			);
			Bugs::activity('view_profile',$args->user);
		},
		'/user/{user}'=>function($res,$args){
			$res->header(
				'Location',
				Router::url(Router::$base.'/~'.$args->user)
			);
		}
	));
?>