<?php
	define('DEBUG',true);
	define('DB_HOST','localhost');
	define('DB_USER','bugs');
	define('DB_PASS','bugs');
	define('DB','bugs');
	define('URL_BASE','/bugs/');
	define('URL_HOST','localhost');
	define('ADMIN_EMAIL','bugs@localhost');
?>